name: Build Bundle

on:
  push:
    tags:
      - "v*"

permissions: write-all

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Getting soft-iot-mapping-devices dependency
        uses: wei/wget@v1
        with:
          args: https://github.com/larsid/soft-iot-mapping-devices/releases/download/v1.0.0/soft-iot-mapping-devices-1.0-SNAPSHOT.jar

      - name: Getting SOFT-IoT-DLT-Client-Tangle-Hornet dependency
        uses: wei/wget@v1
        with:
          args: https://github.com/AllanCapistrano/soft-iot-dlt-client-tangle-hornet/releases/download/v1.0.1/soft-iot-dlt-client-tangle-hornet-1.0-SNAPSHOT.jar

      - name: Getting SOFT-IoT-DLT-ID-Manager dependency
        uses: wei/wget@v1
        with:
          args: https://github.com/larsid/soft-iot-dlt-id-manager/releases/download/v1.1.0/SOFT-IoT-DLT-ID-Manager-1.0-SNAPSHOT.jar

      - name: Installing  soft-iot-mapping-devices
        run: mvn install:install-file -Dfile=./soft-iot-mapping-devices-1.0-SNAPSHOT.jar -DgroupId=io.github.larsid -DartifactId=soft-iot-mapping-devices -Dversion=1.0-SNAPSHOT -Dpackaging=jar
      
      - name: Installing SOFT-IoT-DLT-Client-Tangle
        run: mvn install:install-file -Dfile=./soft-iot-dlt-client-tangle-hornet-1.0-SNAPSHOT.jar -DgroupId=br.uefs.larsid.iot.soft -DartifactId=soft-iot-dlt-client-tangle-hornet -Dversion=1.0-SNAPSHOT -Dpackaging=jar
      
      - name: Installing SOFT-IoT-DLT-ID-Manager
        run: mvn install:install-file -Dfile=./SOFT-IoT-DLT-ID-Manager-1.0-SNAPSHOT.jar -DgroupId=io.github.larsid -DartifactId=SOFT-IoT-DLT-ID-Manager -Dversion=1.0-SNAPSHOT -Dpackaging=jar

      - name: Building the bundle
        run: mvn clean install

      - name: Automatic Releases
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: "${{ secrets.BUILD_BUNDLE_TOKEN }}"
          prerelease: false
          files: |
            target/*.jar